"""Initial migratio

Revision ID: 07c975de50b9
Revises: f2cfa750d037
Create Date: 2025-01-23 14:16:25.424126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c975de50b9'
down_revision: Union[str, None] = 'f2cfa750d037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('user', 'ahe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ahe', sa.INTEGER(), nullable=True))
    op.drop_column('user', 'age')
    # ### end Alembic commands ###